FROM node:20.17

WORKDIR /app

# install stage
COPY pnpm-lock.yaml pnpm-lock.yaml
COPY package.json package.json
RUN npm install -g pnpm

RUN pnpm install

# run
EXPOSE 3000
CMD [ "npm", "run", "dev" ]
