services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  client:
    build:
      context: ./next-app
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    volumes:
      - ./next-app:/app
      - /app/node_modules